version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password #you have to add this in recent version of postgres
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
    depends_on:
      - nodeapp
      - nextapp
  nodeapp:
    build:
      dockerfile: Dockerfile
      context: ./nodeapp
    volumes:
      - /app/node_modules #don't try to override this folder
      - ./nodeapp:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  nextapp:
    build:
      dockerfile: Dockerfile
      context: ./nextapp
    volumes:
      - /app/node_modules
      - ./nextapp:/app
    environment:
      - WDS_SOCKET_PORT=0
# docker-compose up --build
